### ISSUE TITLE
G-force8a-AC : compile error when enabling UBL

### ISSUE THREAD

**Issue by joris57** [LVD-AC/Marlin-AC#32]

**Comment by CaffGeek** [comment]
Same issue here, building on windows in Arduino 1.8.5

I can only find 2 places in code where `probe_pt` is defined
Marlin_main.cpp:2303 `float probe_pt(const float &rx, const float &ry, const bool stow, const uint8_t verbose_level, const bool probe_relative=true, const bool large_clearance=false) {`
and
ubl_G29.cpp:55 `extern float probe_pt(const float &rx, const float &ry, const bool, const uint8_t, const bool=true);`

In order to enable UBL, I just changed the following
https://github.com/CaffGeek/Marlin-AC/commit/b99a9a0c03d7a4810da833a5441e7ac9d05011dd

Is there more I need to do?

**Comment by CaffGeek** [comment]
Feels like a windows linking error between `uint8_t` and `unsigned char` ... I just don't know how to fix it
